name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Clean the repo
        shell: bash
        run: |
          set -eou pipefail
          chmod -R u+rwX "$GITHUB_WORKSPACE" || true
          
          git reset --hard
          git clean -ffdx

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
